void Program();
void Conststate();
void Constdef(int type);
void Varstate();
void Vardef();
int Statehead(int type);
void Funcdef(int type, char *identifier, int ret);
int Paralist();
void Mainfunc();
void Compound();
void Sentencelist();
int Sentence();
void Expression();
void Item(int op);
void Factor();
void Conditionsentence();
void Condition();
void Loop();
void Switch();
void Caselist();
void Case();
void Default();
void Callfunc();
void Paralist2pass();
void Scanfsentence();
void Printfsentence();
void Returnsentence();

int mainflag;
char nowitem[ 200 ];
